[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100
extend-ignore = [
  "D102",
  "D103",
]
exclude = [
  ".git", # speed up
  "tests", # pytest patterns
  "ligapp/tests/*", # pytest patterns
  "__pycache__", # speed up
]
max-complexity = 10

[tool.pytest]
DJANGO_SETTINGS_MODULE = "bc_za.test_settings"
python_files = ["tests.py", "test_*.py"]

[tool.isort]
profile = "black"
